#-----------------------------------------------------------------------
#     This is an example configuration file systemwide for spm.
#     Typical location $HOME/.spm.yaml
#     can be overridden with the --config flag
#-----------------------------------------------------------------------
#     Environment Variables
#     SPM_PKGPASSWORD   - the password for the encrytion of the spm file
#-----------------------------------------------------------------------
pubpkg: https://drive.google.com/
pubart: https://drive.aws.com/

package:
    format: tgz
    workarea: /tmp